import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Professional PDF theme
const pdfTheme = {
  colors: {
    primary: '#000000',      // Black for headers and borders
    secondary: '#333333',    // Dark gray for subheadings
    text: '#000000',         // Black for body text
    lightGray: '#f5f5f5',    // Light gray for backgrounds
    accent: '#2563eb',       // Blue accent (minimal use)
  },
  fonts: {
    primary: 'helvetica',
    sizes: {
      header: 16,
      subheader: 14,
      body: 10,
      small: 8,
    }
  },
  spacing: {
    margin: 10,  // Reduced from 20 to make borders closer to edges
    lineHeight: 5,  // Increased slightly for better readability
    sectionGap: 12,
    paragraphGap: 8,
  },
  layout: {
    pageWidth: 210,
    pageHeight: 297,
    borderWidth: 1,
  }
};

// Extend jsPDF interface for autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: {
      finalY: number;
    };
  }
}

// Layout helper functions
const drawPageFrame = (pdf: jsPDF) => {
  const { margin } = pdfTheme.spacing;
  const { pageWidth, pageHeight, borderWidth } = pdfTheme.layout;
  
  pdf.setDrawColor(pdfTheme.colors.primary);
  pdf.setLineWidth(borderWidth);
  pdf.rect(margin, margin, pageWidth - 2 * margin, pageHeight - 2 * margin);
};

const drawHeaderBar = (pdf: jsPDF, title: string, subtitle: string) => {
  const { margin } = pdfTheme.spacing;
  const { pageWidth } = pdfTheme.layout;
  
  // Black header rectangle
  pdf.setFillColor(pdfTheme.colors.primary);
  pdf.rect(margin + 5, margin + 5, pageWidth - 2 * margin - 10, 25, 'F');
  
  // White text on black background
  pdf.setTextColor(255, 255, 255);
  pdf.setFont(pdfTheme.fonts.primary, 'bold');
  pdf.setFontSize(pdfTheme.fonts.sizes.header);
  pdf.text(title, margin + 10, margin + 18);
  
  pdf.setFontSize(pdfTheme.fonts.sizes.body);
  pdf.text(subtitle, margin + 10, margin + 25);
  
  // Reset text color
  pdf.setTextColor(pdfTheme.colors.text);
};

const addFooter = (pdf: jsPDF, pageNum: number) => {
  const { margin } = pdfTheme.spacing;
  const { pageHeight } = pdfTheme.layout;
  
  pdf.setFontSize(pdfTheme.fonts.sizes.small);
  pdf.setFont(pdfTheme.fonts.primary, 'normal');
  pdf.setTextColor(pdfTheme.colors.secondary);
  
  const footerY = pageHeight - margin + 5;
  pdf.text(`Page ${pageNum}`, margin, footerY);
  pdf.text('Generated by Athlete360', margin + 150, footerY);
  
  // Reset text color
  pdf.setTextColor(pdfTheme.colors.text);
};

const addSectionHeader = (pdf: jsPDF, title: string, currentY: number): number => {
  pdf.setFont(pdfTheme.fonts.primary, 'bold');
  pdf.setFontSize(pdfTheme.fonts.sizes.subheader);
  pdf.text(title, pdfTheme.spacing.margin + 5, currentY);
  
  // Add underline
  const textWidth = pdf.getTextWidth(title);
  pdf.setLineWidth(0.5);
  pdf.line(pdfTheme.spacing.margin + 5, currentY + 2, pdfTheme.spacing.margin + 5 + textWidth, currentY + 2);
  
  return currentY + pdfTheme.spacing.sectionGap;
};

const addText = (pdf: jsPDF, text: string, currentY: number, options: any = {}): number => {
  const { margin } = pdfTheme.spacing;
  const maxWidth = 190;  // Increased width due to smaller margins
  const leftIndent = options.indent || 10; // Content indentation from margin
  
  pdf.setFont(pdfTheme.fonts.primary, options.weight || 'normal');
  pdf.setFontSize(options.fontSize || pdfTheme.fonts.sizes.body);
  
  if (text.length > 100) {
    const lines = pdf.splitTextToSize(text, maxWidth - leftIndent);
    pdf.text(lines, margin + leftIndent, currentY, { maxWidth: maxWidth - leftIndent, lineHeightFactor: 1.2 });
    return currentY + (lines.length * pdfTheme.spacing.lineHeight) + (options.extraSpacing || 0);
  } else {
    pdf.text(text, margin + leftIndent, currentY, { maxWidth: maxWidth - leftIndent });
    return currentY + pdfTheme.spacing.lineHeight + (options.extraSpacing || 0);
  }
};

// Data extraction functions
const extractAthleteInfo = (data: any) => {
  let athleteInfo = {
    name: '',
    country: '',
    sport: '',
    rank: '',
    achievements: [] as any[]
  };

  if (data.data) {
    const bioData = data.data;
    athleteInfo.name = bioData.personalInfo?.name || bioData.name || '';
    athleteInfo.country = bioData.personalInfo?.nationality || bioData.nationality || bioData.country || '';
    athleteInfo.sport = bioData.personalInfo?.sport || bioData.sport || '';
    athleteInfo.rank = bioData.personalInfo?.worldRanking || bioData.worldRanking || bioData.rank || '';
    athleteInfo.achievements = bioData.personalInfo?.majorAchievements || bioData.majorAchievements || bioData.achievements || [];
  } else if (data.athlete_name || data.nationality || data.sport) {
    athleteInfo.name = data.athlete_name || '';
    athleteInfo.country = data.nationality || '';
    athleteInfo.sport = data.sport || '';
  }

  return athleteInfo;
};

const extractCompetitions = (data: any) => {
  let competitions: any[] = [];
  
  if (data.career_phases && Array.isArray(data.career_phases)) {
    data.career_phases.forEach((phase: any) => {
      if (phase.key_achievements && Array.isArray(phase.key_achievements)) {
        phase.key_achievements.forEach((achievement: any) => {
          competitions.push({
            year: achievement.year || '',
            event: achievement.event_name || achievement.competition || '',
            result: achievement.result || achievement.medal || '',
            tier: achievement.event_tier || '',
            notes: achievement.notes || ''
          });
        });
      }
    });
  }
  
  return competitions;
};

const parseBioSections = (bioText: string) => {
  if (!bioText) return {};
  
  const sections: any = {};
  
  // Look for introduction (current status)
  const introMatch = bioText.match(/^(.*?)\n\n/);
  if (introMatch) {
    sections.introduction = introMatch[1].trim();
  }
  
  // Look for overall story section
  const storyMatch = bioText.match(/Players' overall story and what they're known for[\s\S]*?\n\n([\s\S]*?)(?:\n\n|$)/);
  if (storyMatch) {
    sections.overallStory = storyMatch[1].trim();
  } else {
    // Fallback - use the middle portion of bio
    const parts = bioText.split('\n\n');
    if (parts.length > 1) {
      sections.overallStory = parts.slice(1, -1).join('\n\n');
    }
  }
  
  // Look for career record section
  const careerMatch = bioText.match(/career record|rankings|record/i);
  if (careerMatch) {
    const careerText = bioText.substring(careerMatch.index || 0);
    const endMatch = careerText.match(/\n\n/);
    sections.careerRecord = endMatch ? careerText.substring(0, endMatch.index) : careerText;
  }
  
  return sections;
};

// Specific PDF generators
const generateBioPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  const bio = data.data?.bio || data.bio || '';
  const bioSections = parseBioSections(bio);
  
  // Athlete Information Section
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold', indent: 10 });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY, { indent: 10 });
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY, { indent: 10 });
  }
  if (athleteInfo.rank) {
    currentY = addText(pdf, `Current Rank: ${athleteInfo.rank}`, currentY, { indent: 10 });
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Bio Content
  if (bioSections.introduction) {
    currentY = addSectionHeader(pdf, 'Current Status', currentY);
    currentY = addText(pdf, bioSections.introduction, currentY, { 
      indent: 10,
      extraSpacing: pdfTheme.spacing.paragraphGap 
    });
  }
  
  if (bioSections.overallStory) {
    currentY = addSectionHeader(pdf, 'Career Overview', currentY);
    currentY = addText(pdf, bioSections.overallStory, currentY, { 
      indent: 10,
      extraSpacing: pdfTheme.spacing.paragraphGap 
    });
  }
  
  // Achievements
  if (athleteInfo.achievements && athleteInfo.achievements.length > 0) {
    currentY = addSectionHeader(pdf, 'Major Achievements', currentY);
    
    athleteInfo.achievements.forEach((achievement: any) => {
      const achievementText = typeof achievement === 'string' ? achievement : 
        `${achievement.year || ''} - ${achievement.event || achievement.competition || ''}: ${achievement.result || achievement.medal || ''}`;
      currentY = addText(pdf, `• ${achievementText}`, currentY, { indent: 15 });
    });
  }
  
  return currentY;
};

const generateRankPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  try {
    const athleteInfo = extractAthleteInfo(data);
    
    // Athlete Information
    currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
    
    if (athleteInfo.name) {
      currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold', indent: 10 });
    }
    if (athleteInfo.country) {
      currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY, { indent: 10 });
    }
    if (athleteInfo.sport) {
      currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY, { indent: 10 });
    }
    
    currentY += pdfTheme.spacing.sectionGap;
    
    // Career Phases with individual tables for each phase
    if (data.career_phases && Array.isArray(data.career_phases)) {
      currentY = addSectionHeader(pdf, 'Career Phases & Competition History', currentY);
      
      data.career_phases.forEach((phase: any, phaseIndex: number) => {
        if (phase.period && phase.phase_name) {
          // Phase header
          currentY = addText(pdf, `${phase.period}: ${phase.phase_name}`, currentY, { 
            weight: 'bold', 
            fontSize: pdfTheme.fonts.sizes.subheader,
            indent: 10,
            extraSpacing: 3
          });
          
          if (phase.description) {
            currentY = addText(pdf, phase.description, currentY, { 
              indent: 15,
              extraSpacing: 5
            });
          }
          
          // Generate manual table for this phase's competitions
          if (phase.key_achievements && Array.isArray(phase.key_achievements) && phase.key_achievements.length > 0) {
            try {
              
              // Table configuration - centered table that respects page borders
              const columnWidths = [18, 85, 35, 37]; // Year, Event, Result, Tier - totals 175
              const tableWidth = columnWidths.reduce((a, b) => a + b, 0);
              const pageWidth = pdfTheme.layout.pageWidth;
              const tableStartX = (pageWidth - tableWidth) / 2; // Center the table
              const tableStartY = currentY;
              const rowHeight = 12; // Slightly taller rows
              const headerHeight = 14;
              
              // Check if table will fit on current page, if not create new page
              const tableHeight = headerHeight + (phase.key_achievements.length * rowHeight);
              const remainingPageSpace = pdfTheme.layout.pageHeight - currentY - pdfTheme.spacing.margin;
              
              let actualTableStartY = tableStartY;
              
              if (tableHeight > remainingPageSpace) {
                pdf.addPage();
                
                // Draw page border on new page
                pdf.setDrawColor(pdfTheme.colors.primary);
                pdf.setLineWidth(pdfTheme.layout.borderWidth);
                pdf.rect(
                  pdfTheme.spacing.margin, 
                  pdfTheme.spacing.margin, 
                  pdfTheme.layout.pageWidth - (pdfTheme.spacing.margin * 2), 
                  pdfTheme.layout.pageHeight - (pdfTheme.spacing.margin * 2)
                );
                
                currentY = 40; // Start near top of new page
                actualTableStartY = currentY;
              }
              
              // Draw table header
              pdf.setFillColor(0, 0, 0); // Black background
              pdf.rect(tableStartX, actualTableStartY, columnWidths.reduce((a, b) => a + b, 0), headerHeight, 'F');
              
              // Header text
              pdf.setTextColor(255, 255, 255); // White text
              pdf.setFont(pdfTheme.fonts.primary, 'bold');
              pdf.setFontSize(9);
              
              let headerX = tableStartX + 2;
              pdf.text('Year', headerX, actualTableStartY + 8);
              headerX += columnWidths[0];
              pdf.text('Event', headerX, actualTableStartY + 8);
              headerX += columnWidths[1];
              pdf.text('Result', headerX, actualTableStartY + 8);
              headerX += columnWidths[2];
              pdf.text('Tier', headerX, actualTableStartY + 8);
              
              // Reset text color for table content
              pdf.setTextColor(0, 0, 0);
              pdf.setFont(pdfTheme.fonts.primary, 'normal');
              pdf.setFontSize(8);
              
              let currentRowY = actualTableStartY + headerHeight;
              
              // Draw table rows
              phase.key_achievements.forEach((achievement: any, index: number) => {
                const rawRowData = [
                  String(achievement.year || ''),
                  String(achievement.event_name || ''),
                  String(achievement.result || ''),
                  String(achievement.event_tier || '')
                ];
                
                // Fit text to column widths
                const rowData = rawRowData.map((text, colIndex) => {
                  const maxWidth = columnWidths[colIndex] - 4; // Account for padding
                  const lines = pdf.splitTextToSize(text, maxWidth);
                  return lines.length > 1 ? lines[0] : text; // Use first line if wrapped
                });
                
                // Alternate row background
                if (index % 2 === 1) {
                  pdf.setFillColor(240, 240, 240); // Light gray
                  pdf.rect(tableStartX, currentRowY, columnWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
                }
                
                // Draw cell borders
                pdf.setDrawColor(200, 200, 200);
                pdf.setLineWidth(0.2);
                let cellX = tableStartX;
                columnWidths.forEach((width, colIndex) => {
                  pdf.rect(cellX, currentRowY, width, rowHeight);
                  cellX += width;
                });
                
                // Add text content with proper positioning
                let textX = tableStartX + 2;
                rowData.forEach((text, colIndex) => {
                  // Center text vertically in cell
                  pdf.text(text, textX, currentRowY + (rowHeight / 2) + 2);
                  textX += columnWidths[colIndex];
                });
                
                currentRowY += rowHeight;
              });
              
              // Draw table border
              pdf.setDrawColor(0, 0, 0);
              pdf.setLineWidth(0.5);
              pdf.rect(tableStartX, actualTableStartY, columnWidths.reduce((a, b) => a + b, 0), headerHeight + (phase.key_achievements.length * rowHeight));
              
              currentY = currentRowY + 5;
              
            } catch (tableError) {
              currentY = addText(pdf, `• Competition data for ${phase.period} could not be displayed`, currentY, { indent: 15 });
              currentY += 5;
            }
          } else {
            currentY = addText(pdf, '• No competitions recorded for this phase', currentY, { indent: 15 });
            currentY += 5;
          }
          
          // Add spacing between phases
          if (phaseIndex < data.career_phases.length - 1) {
            currentY += pdfTheme.spacing.sectionGap;
          }
        }
      });
    } else {
      currentY = addText(pdf, 'No career phase information available.', currentY, { indent: 10 });
    }
    
  } catch (error) {
    console.error('Rank PDF generation error:', error);
    currentY = addText(pdf, 'Error generating competitive history report.', currentY, { indent: 10 });
  }
  
  return currentY;
};

const generateStrengthsPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  
  // Athlete Information
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold', indent: 10 });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY, { indent: 10 });
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY, { indent: 10 });
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Strengths Analysis
  let strengths: any[] = [];
  
  if (Array.isArray(data.strengths)) {
    strengths = data.strengths;
  } else if (typeof data === 'string') {
    try {
      const parsed = JSON.parse(data);
      strengths = parsed.strengths || [];
    } catch (e) {
      // Handle parsing error
    }
  }
  
  if (strengths.length > 0) {
    currentY = addSectionHeader(pdf, 'Strengths Analysis', currentY);
    
    strengths.forEach((strength: any, index: number) => {
      currentY = addText(pdf, `${index + 1}. ${strength.title || strength.name || 'Strength'}`, currentY, { 
        weight: 'bold',
        indent: 10,
        fontSize: pdfTheme.fonts.sizes.body + 1
      });
      
      if (strength.description) {
        currentY = addText(pdf, strength.description, currentY, { indent: 15 });
      }
      
      if (strength.evidence && Array.isArray(strength.evidence)) {
        currentY = addText(pdf, 'Evidence:', currentY, { weight: 'bold', indent: 15 });
        strength.evidence.forEach((evidence: any) => {
          const evidenceText = typeof evidence === 'string' ? evidence : evidence.description || evidence.text || '';
          currentY = addText(pdf, `• ${evidenceText}`, currentY, { indent: 20 });
        });
      }
      
      currentY += pdfTheme.spacing.paragraphGap;
    });
  } else {
    currentY = addText(pdf, 'No strengths data available for analysis.', currentY, { indent: 10 });
  }
  
  return currentY;
};

const generateWeaknessesPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  
  // Athlete Information
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold', indent: 10 });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY, { indent: 10 });
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY, { indent: 10 });
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Weaknesses Analysis
  let weaknesses: any[] = [];
  
  if (Array.isArray(data.weaknesses)) {
    weaknesses = data.weaknesses;
  } else if (typeof data === 'string') {
    try {
      const parsed = JSON.parse(data);
      weaknesses = parsed.weaknesses || [];
    } catch (e) {
      // Handle parsing error
    }
  }
  
  if (weaknesses.length > 0) {
    currentY = addSectionHeader(pdf, 'Areas for Improvement', currentY);
    
    weaknesses.forEach((weakness: any, index: number) => {
      currentY = addText(pdf, `${index + 1}. ${weakness.title || weakness.name || 'Area for Improvement'}`, currentY, { 
        weight: 'bold',
        indent: 10,
        fontSize: pdfTheme.fonts.sizes.body + 1
      });
      
      if (weakness.description) {
        currentY = addText(pdf, weakness.description, currentY, { indent: 15 });
      }
      
      if (weakness.evidence && Array.isArray(weakness.evidence)) {
        currentY = addText(pdf, 'Evidence:', currentY, { weight: 'bold', indent: 15 });
        weakness.evidence.forEach((evidence: any) => {
          const evidenceText = typeof evidence === 'string' ? evidence : evidence.description || evidence.text || '';
          currentY = addText(pdf, `• ${evidenceText}`, currentY, { indent: 20 });
        });
      }
      
      currentY += pdfTheme.spacing.paragraphGap;
    });
  } else {
    currentY = addText(pdf, 'No areas for improvement identified in this analysis.', currentY, { indent: 10 });
  }
  
  return currentY;
};

// Main professional PDF generator function
export const generateProfessionalPdf = async ({
  type,
  data,
  createdAt,
  athleteName
}: {
  type: string;
  data: any;
  createdAt?: string;
  athleteName?: string;
}): Promise<Blob> => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  // Draw page frame (border)
  drawPageFrame(pdf);
  
  // Add header with title and subtitle
  const title = getReportTitle(type);
  const subtitle = `${athleteName || 'Athlete Analysis'} • ${new Date(createdAt || Date.now()).toLocaleDateString()}`;
  drawHeaderBar(pdf, title, subtitle);
  
  // Generate content based on type
  let finalY: number;
  switch (type) {
    case 'bio':
      finalY = generateBioPDF(pdf, data);
      break;
    case 'rank':
      finalY = generateRankPDF(pdf, data);
      break;
    case 'strengths':
      finalY = generateStrengthsPDF(pdf, data);
      break;
    case 'weaknesses':
      finalY = generateWeaknessesPDF(pdf, data);
      break;
    default:
      finalY = addText(pdf, 'Analysis type not supported for PDF export.', 60);
  }
  
  // Add footer
  addFooter(pdf, 1);
  
  return pdf.output('blob');
};

// Helper function to get report title
const getReportTitle = (type: string): string => {
  const titles: { [key: string]: string } = {
    bio: 'Bio Analysis Report',
    rank: 'Competitive History Report',
    strengths: 'Strengths Analysis Report',
    weaknesses: 'Areas for Improvement Report',
    development: 'Development Plan Report',
    nutrition: 'Nutrition Plan Report',
    beat: 'Beat Strategies Report'
  };
  
  return titles[type] || 'Analysis Report';
};