import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Professional PDF theme
const pdfTheme = {
  colors: {
    primary: '#000000',      // Black for headers and borders
    secondary: '#333333',    // Dark gray for subheadings
    text: '#000000',         // Black for body text
    lightGray: '#f5f5f5',    // Light gray for backgrounds
    accent: '#2563eb',       // Blue accent (minimal use)
  },
  fonts: {
    primary: 'helvetica',
    sizes: {
      header: 16,
      subheader: 14,
      body: 10,
      small: 8,
    }
  },
  spacing: {
    margin: 20,
    lineHeight: 4,
    sectionGap: 10,
    paragraphGap: 6,
  },
  layout: {
    pageWidth: 210,
    pageHeight: 297,
    borderWidth: 1,
  }
};

// Extend jsPDF interface for autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: {
      finalY: number;
    };
  }
}

// Layout helper functions
const drawPageFrame = (pdf: jsPDF) => {
  const { margin } = pdfTheme.spacing;
  const { pageWidth, pageHeight, borderWidth } = pdfTheme.layout;
  
  pdf.setDrawColor(pdfTheme.colors.primary);
  pdf.setLineWidth(borderWidth);
  pdf.rect(margin, margin, pageWidth - 2 * margin, pageHeight - 2 * margin);
};

const drawHeaderBar = (pdf: jsPDF, title: string, subtitle: string) => {
  const { margin } = pdfTheme.spacing;
  const { pageWidth } = pdfTheme.layout;
  
  // Black header rectangle
  pdf.setFillColor(pdfTheme.colors.primary);
  pdf.rect(margin + 5, margin + 5, pageWidth - 2 * margin - 10, 25, 'F');
  
  // White text on black background
  pdf.setTextColor(255, 255, 255);
  pdf.setFont(pdfTheme.fonts.primary, 'bold');
  pdf.setFontSize(pdfTheme.fonts.sizes.header);
  pdf.text(title, margin + 10, margin + 18);
  
  pdf.setFontSize(pdfTheme.fonts.sizes.body);
  pdf.text(subtitle, margin + 10, margin + 25);
  
  // Reset text color
  pdf.setTextColor(pdfTheme.colors.text);
};

const addFooter = (pdf: jsPDF, pageNum: number) => {
  const { margin } = pdfTheme.spacing;
  const { pageHeight } = pdfTheme.layout;
  
  pdf.setFontSize(pdfTheme.fonts.sizes.small);
  pdf.setFont(pdfTheme.fonts.primary, 'normal');
  pdf.setTextColor(pdfTheme.colors.secondary);
  
  const footerY = pageHeight - margin + 5;
  pdf.text(`Page ${pageNum}`, margin, footerY);
  pdf.text('Generated by Athlete360', margin + 150, footerY);
  
  // Reset text color
  pdf.setTextColor(pdfTheme.colors.text);
};

const addSectionHeader = (pdf: jsPDF, title: string, currentY: number): number => {
  pdf.setFont(pdfTheme.fonts.primary, 'bold');
  pdf.setFontSize(pdfTheme.fonts.sizes.subheader);
  pdf.text(title, pdfTheme.spacing.margin + 10, currentY);
  
  // Add underline
  const textWidth = pdf.getTextWidth(title);
  pdf.setLineWidth(0.5);
  pdf.line(pdfTheme.spacing.margin + 10, currentY + 2, pdfTheme.spacing.margin + 10 + textWidth, currentY + 2);
  
  return currentY + pdfTheme.spacing.sectionGap;
};

const addText = (pdf: jsPDF, text: string, currentY: number, options: any = {}): number => {
  const { margin } = pdfTheme.spacing;
  const maxWidth = 170;
  
  pdf.setFont(pdfTheme.fonts.primary, options.weight || 'normal');
  pdf.setFontSize(options.fontSize || pdfTheme.fonts.sizes.body);
  
  if (text.length > 100) {
    const lines = pdf.splitTextToSize(text, maxWidth);
    pdf.text(lines, margin + 10, currentY);
    return currentY + (lines.length * pdfTheme.spacing.lineHeight) + (options.extraSpacing || 0);
  } else {
    pdf.text(text, margin + 10, currentY);
    return currentY + pdfTheme.spacing.lineHeight + (options.extraSpacing || 0);
  }
};

// Data extraction functions
const extractAthleteInfo = (data: any) => {
  let athleteInfo = {
    name: '',
    country: '',
    sport: '',
    rank: '',
    achievements: [] as any[]
  };

  if (data.data) {
    const bioData = data.data;
    athleteInfo.name = bioData.personalInfo?.name || bioData.name || '';
    athleteInfo.country = bioData.personalInfo?.nationality || bioData.nationality || bioData.country || '';
    athleteInfo.sport = bioData.personalInfo?.sport || bioData.sport || '';
    athleteInfo.rank = bioData.personalInfo?.worldRanking || bioData.worldRanking || bioData.rank || '';
    athleteInfo.achievements = bioData.personalInfo?.majorAchievements || bioData.majorAchievements || bioData.achievements || [];
  } else if (data.athlete_name || data.nationality || data.sport) {
    athleteInfo.name = data.athlete_name || '';
    athleteInfo.country = data.nationality || '';
    athleteInfo.sport = data.sport || '';
  }

  return athleteInfo;
};

const extractCompetitions = (data: any) => {
  let competitions: any[] = [];
  
  if (data.career_phases && Array.isArray(data.career_phases)) {
    data.career_phases.forEach((phase: any) => {
      if (phase.key_achievements && Array.isArray(phase.key_achievements)) {
        phase.key_achievements.forEach((achievement: any) => {
          competitions.push({
            year: achievement.year || '',
            event: achievement.event_name || achievement.competition || '',
            result: achievement.result || achievement.medal || '',
            tier: achievement.event_tier || '',
            notes: achievement.notes || ''
          });
        });
      }
    });
  }
  
  return competitions;
};

const parseBioSections = (bioText: string) => {
  if (!bioText) return {};
  
  const sections: any = {};
  
  // Look for introduction (current status)
  const introMatch = bioText.match(/^(.*?)\n\n/);
  if (introMatch) {
    sections.introduction = introMatch[1].trim();
  }
  
  // Look for overall story section
  const storyMatch = bioText.match(/Players' overall story and what they're known for[\s\S]*?\n\n([\s\S]*?)(?:\n\n|$)/);
  if (storyMatch) {
    sections.overallStory = storyMatch[1].trim();
  } else {
    // Fallback - use the middle portion of bio
    const parts = bioText.split('\n\n');
    if (parts.length > 1) {
      sections.overallStory = parts.slice(1, -1).join('\n\n');
    }
  }
  
  // Look for career record section
  const careerMatch = bioText.match(/career record|rankings|record/i);
  if (careerMatch) {
    const careerText = bioText.substring(careerMatch.index || 0);
    const endMatch = careerText.match(/\n\n/);
    sections.careerRecord = endMatch ? careerText.substring(0, endMatch.index) : careerText;
  }
  
  return sections;
};

// Specific PDF generators
const generateBioPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  const bio = data.data?.bio || data.bio || '';
  const bioSections = parseBioSections(bio);
  
  // Athlete Information Section
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold' });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY);
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY);
  }
  if (athleteInfo.rank) {
    currentY = addText(pdf, `Current Rank: ${athleteInfo.rank}`, currentY);
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Bio Content
  if (bioSections.introduction) {
    currentY = addSectionHeader(pdf, 'Current Status', currentY);
    currentY = addText(pdf, bioSections.introduction, currentY, { extraSpacing: pdfTheme.spacing.paragraphGap });
  }
  
  if (bioSections.overallStory) {
    currentY = addSectionHeader(pdf, 'Career Overview', currentY);
    currentY = addText(pdf, bioSections.overallStory, currentY, { extraSpacing: pdfTheme.spacing.paragraphGap });
  }
  
  // Achievements
  if (athleteInfo.achievements && athleteInfo.achievements.length > 0) {
    currentY = addSectionHeader(pdf, 'Major Achievements', currentY);
    
    athleteInfo.achievements.forEach((achievement: any) => {
      const achievementText = typeof achievement === 'string' ? achievement : 
        `${achievement.year || ''} - ${achievement.event || achievement.competition || ''}: ${achievement.result || achievement.medal || ''}`;
      currentY = addText(pdf, `• ${achievementText}`, currentY);
    });
  }
  
  return currentY;
};

const generateRankPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  const competitions = extractCompetitions(data);
  
  // Athlete Information
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold' });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY);
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY);
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Career Phases
  if (data.career_phases && Array.isArray(data.career_phases)) {
    currentY = addSectionHeader(pdf, 'Career Phases', currentY);
    
    data.career_phases.forEach((phase: any) => {
      currentY = addText(pdf, `${phase.period}: ${phase.phase_name}`, currentY, { weight: 'bold' });
      if (phase.description) {
        currentY = addText(pdf, phase.description, currentY, { extraSpacing: pdfTheme.spacing.paragraphGap });
      }
    });
  }
  
  // Competition History Table
  if (competitions.length > 0) {
    currentY += pdfTheme.spacing.sectionGap;
    currentY = addSectionHeader(pdf, 'Competition History', currentY);
    
    const tableData = competitions.map(comp => [
      comp.year,
      comp.event,
      comp.result,
      comp.tier || ''
    ]);
    
    pdf.autoTable({
      head: [['Year', 'Event', 'Result', 'Tier']],
      body: tableData,
      startY: currentY,
      margin: { left: pdfTheme.spacing.margin + 10 },
      styles: {
        fontSize: pdfTheme.fonts.sizes.body,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: pdfTheme.colors.primary,
        textColor: 255,
        fontSize: pdfTheme.fonts.sizes.body,
      },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 80 },
        2: { cellWidth: 35 },
        3: { cellWidth: 30 },
      }
    });
    
    currentY = pdf.lastAutoTable.finalY + pdfTheme.spacing.sectionGap;
  }
  
  return currentY;
};

const generateStrengthsPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  
  // Athlete Information
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold' });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY);
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY);
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Strengths Analysis
  let strengths: any[] = [];
  
  if (Array.isArray(data.strengths)) {
    strengths = data.strengths;
  } else if (typeof data === 'string') {
    try {
      const parsed = JSON.parse(data);
      strengths = parsed.strengths || [];
    } catch (e) {
      // Handle parsing error
    }
  }
  
  if (strengths.length > 0) {
    currentY = addSectionHeader(pdf, 'Strengths Analysis', currentY);
    
    strengths.forEach((strength: any, index: number) => {
      currentY = addText(pdf, `${index + 1}. ${strength.title || strength.name || 'Strength'}`, currentY, { weight: 'bold' });
      
      if (strength.description) {
        currentY = addText(pdf, strength.description, currentY);
      }
      
      if (strength.evidence && Array.isArray(strength.evidence)) {
        currentY = addText(pdf, 'Evidence:', currentY, { weight: 'bold' });
        strength.evidence.forEach((evidence: any) => {
          const evidenceText = typeof evidence === 'string' ? evidence : evidence.description || evidence.text || '';
          currentY = addText(pdf, `• ${evidenceText}`, currentY);
        });
      }
      
      currentY += pdfTheme.spacing.paragraphGap;
    });
  } else {
    currentY = addText(pdf, 'No strengths data available for analysis.', currentY);
  }
  
  return currentY;
};

const generateWeaknessesPDF = (pdf: jsPDF, data: any): number => {
  let currentY = 60;
  
  const athleteInfo = extractAthleteInfo(data);
  
  // Athlete Information
  currentY = addSectionHeader(pdf, 'Athlete Information', currentY);
  
  if (athleteInfo.name) {
    currentY = addText(pdf, `Name: ${athleteInfo.name}`, currentY, { weight: 'bold' });
  }
  if (athleteInfo.country) {
    currentY = addText(pdf, `Country: ${athleteInfo.country}`, currentY);
  }
  if (athleteInfo.sport) {
    currentY = addText(pdf, `Sport: ${athleteInfo.sport}`, currentY);
  }
  
  currentY += pdfTheme.spacing.sectionGap;
  
  // Weaknesses Analysis
  let weaknesses: any[] = [];
  
  if (Array.isArray(data.weaknesses)) {
    weaknesses = data.weaknesses;
  } else if (typeof data === 'string') {
    try {
      const parsed = JSON.parse(data);
      weaknesses = parsed.weaknesses || [];
    } catch (e) {
      // Handle parsing error
    }
  }
  
  if (weaknesses.length > 0) {
    currentY = addSectionHeader(pdf, 'Areas for Improvement', currentY);
    
    weaknesses.forEach((weakness: any, index: number) => {
      currentY = addText(pdf, `${index + 1}. ${weakness.title || weakness.name || 'Area for Improvement'}`, currentY, { weight: 'bold' });
      
      if (weakness.description) {
        currentY = addText(pdf, weakness.description, currentY);
      }
      
      if (weakness.evidence && Array.isArray(weakness.evidence)) {
        currentY = addText(pdf, 'Evidence:', currentY, { weight: 'bold' });
        weakness.evidence.forEach((evidence: any) => {
          const evidenceText = typeof evidence === 'string' ? evidence : evidence.description || evidence.text || '';
          currentY = addText(pdf, `• ${evidenceText}`, currentY);
        });
      }
      
      currentY += pdfTheme.spacing.paragraphGap;
    });
  } else {
    currentY = addText(pdf, 'No areas for improvement identified in this analysis.', currentY);
  }
  
  return currentY;
};

// Main professional PDF generator function
export const generateProfessionalPdf = async ({
  type,
  data,
  createdAt,
  athleteName
}: {
  type: string;
  data: any;
  createdAt?: string;
  athleteName?: string;
}): Promise<Blob> => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  // Draw page frame (border)
  drawPageFrame(pdf);
  
  // Add header with title and subtitle
  const title = getReportTitle(type);
  const subtitle = `${athleteName || 'Athlete Analysis'} • ${new Date(createdAt || Date.now()).toLocaleDateString()}`;
  drawHeaderBar(pdf, title, subtitle);
  
  // Generate content based on type
  let finalY: number;
  switch (type) {
    case 'bio':
      finalY = generateBioPDF(pdf, data);
      break;
    case 'rank':
      finalY = generateRankPDF(pdf, data);
      break;
    case 'strengths':
      finalY = generateStrengthsPDF(pdf, data);
      break;
    case 'weaknesses':
      finalY = generateWeaknessesPDF(pdf, data);
      break;
    default:
      finalY = addText(pdf, 'Analysis type not supported for PDF export.', 60);
  }
  
  // Add footer
  addFooter(pdf, 1);
  
  return pdf.output('blob');
};

// Helper function to get report title
const getReportTitle = (type: string): string => {
  const titles: { [key: string]: string } = {
    bio: 'Bio Analysis Report',
    rank: 'Competitive History Report',
    strengths: 'Strengths Analysis Report',
    weaknesses: 'Areas for Improvement Report',
    development: 'Development Plan Report',
    nutrition: 'Nutrition Plan Report',
    beat: 'Beat Strategies Report'
  };
  
  return titles[type] || 'Analysis Report';
};