import { Builder, WebDriver, By, until } from 'selenium-webdriver';
import chrome from 'selenium-webdriver/chrome';
import OpenAI from 'openai';

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || process.env.GOOGLE_API_KEY
});

interface ScrapedImage {
  url: string;
  source: string;
  altText?: string;
  context?: string;
  confidence: number;
}

interface AthleteContext {
  name: string;
  sport?: string;
  country?: string;
  personalInfo?: any;
}

// Main function: Simplified Selenium + GPT-5 pipeline (following Python example pattern)
export async function searchAthleteImageWithScraping(
  athleteName: string, 
  sport?: string,
  country?: string, 
  personalInfo?: any
): Promise<string | null> {
  try {
    console.log(`🔍 Starting simplified Selenium + GPT-5 image search for ${athleteName}...`);
    
    // Step 1: Use GPT-5 to generate optimized search query
    const searchQuery = await generateOptimalSearchQuery(athleteName, sport, country);
    if (!searchQuery) {
      console.log(`❌ Could not generate search query for ${athleteName}`);
      return null;
    }

    console.log(`🤖 GPT-5 generated search query: ${searchQuery}`);

    // Step 2: Use Selenium to scrape Google Images with the optimized query
    const imageUrls = await scrapeGoogleImagesSimplified(searchQuery, 10);
    
    if (imageUrls.length === 0) {
      console.log(`❌ No images found for query: ${searchQuery}`);
      return null;
    }

    console.log(`📸 Found ${imageUrls.length} candidate images from Google Images`);

    // Step 3: Use GPT-5 to select the best image URL
    const selectedImageUrl = await selectBestImageWithGPT5(imageUrls, athleteName, sport, country);
    
    if (!selectedImageUrl) {
      console.log(`❌ GPT-5 could not select a suitable image for ${athleteName}`);
      return null;
    }

    // Step 4: Validate the selected image URL
    const validatedUrl = await validateImageUrl(selectedImageUrl);
    
    if (validatedUrl) {
      console.log(`✅ Successfully found and validated image for ${athleteName}: ${selectedImageUrl}`);
      return selectedImageUrl;
    } else {
      console.log(`❌ Selected image failed validation for ${athleteName}`);
      return null;
    }

  } catch (error) {
    console.error(`❌ Error in simplified Selenium + GPT-5 image search for ${athleteName}:`, error);
    return null;
  }
}

// Step 1: Use GPT-5 to generate optimal search query (following Python example)
async function generateOptimalSearchQuery(
  athleteName: string, 
  sport?: string, 
  country?: string
): Promise<string | null> {
  try {
    const contextInfo = [];
    if (sport) contextInfo.push(sport);
    if (country) contextInfo.push(country);
    
    const prompt = `The user wants to see images of the athlete: ${athleteName}.
Return ONLY the best Google Images search query for this specific athlete.
IMPORTANT: Always include the athlete's full name in the search query.

Examples:
"Habiba Wael Emerah Taekwondo site:gettyimages.com OR site:fiba.basketball"
"Serena Williams Tennis site:espn.com OR site:usopen.org"  
"Rafael Nadal Tennis site:gettyimages.com OR site:atptour.com"

Create a similar search query for: ${athleteName} (${contextInfo.join(' ')})`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [{ role: "user", content: prompt }],
      max_tokens: 100,
      temperature: 0.3
    });

    const searchQuery = response.choices[0]?.message?.content?.trim();
    if (!searchQuery) {
      console.log(`❌ No search query generated by GPT-5`);
      return null;
    }

    return searchQuery;
  } catch (error) {
    console.error(`❌ Error generating search query:`, error);
    return null;
  }
}

// Step 2: Simplified Google Images scraping (following Python example)
async function scrapeGoogleImagesSimplified(
  searchQuery: string, 
  maxImages: number = 10
): Promise<string[]> {
  const imageUrls: string[] = [];
  
  try {
    console.log(`🔍 Scraping Google Images with query: ${searchQuery}`);
    
    // Set up Chrome options for headless browsing
    const chromeOptions = new chrome.Options();
    chromeOptions.addArguments('--headless');
    chromeOptions.addArguments('--no-sandbox');
    chromeOptions.addArguments('--disable-setuid-sandbox');
    chromeOptions.addArguments('--disable-dev-shm-usage');
    chromeOptions.addArguments('--disable-gpu');
    chromeOptions.addArguments('--disable-features=VizDisplayCompositor');
    chromeOptions.addArguments('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');

    const driver = await new Builder()
      .forBrowser('chrome')
      .setChromeOptions(chromeOptions)
      .build();
    
    try {
      // Navigate to Google Images with the search query
      const googleImagesUrl = `https://www.google.com/search?tbm=isch&q=${encodeURIComponent(searchQuery)}`;
      await driver.get(googleImagesUrl);
      
      // Wait a moment for images to load
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Find all image elements
      const imgElements = await driver.findElements(By.css('img'));
      
      for (const imgElement of imgElements) {
        if (imageUrls.length >= maxImages) break;
        
        try {
          const src = await imgElement.getAttribute('src');
          if (src && src.includes('http') && !src.includes('google') && !src.includes('gstatic')) {
            imageUrls.push(src);
          }
        } catch (elementError) {
          console.log(`⚠️ Error processing image element:`, elementError);
          continue;
        }
      }
      
    } finally {
      await driver.quit();
    }
    
    console.log(`📸 Found ${imageUrls.length} image URLs from Google Images`);
    
  } catch (error) {
    console.error(`❌ Error scraping Google Images:`, error);
  }
  
  return imageUrls;
}

// Step 3: Use GPT-5 to select the best image from URLs
async function selectBestImageWithGPT5(
  imageUrls: string[], 
  athleteName: string, 
  sport?: string, 
  country?: string
): Promise<string | null> {
  try {
    console.log(`🤖 Using GPT-5 to select best image from ${imageUrls.length} candidates for ${athleteName}...`);
    
    // Build context for GPT-5
    const contextInfo = [];
    if (sport) contextInfo.push(`Sport: ${sport}`);
    if (country) contextInfo.push(`Country: ${country}`);
    
    const urlList = imageUrls.map((url, index) => `${index + 1}. ${url}`).join('\n');
    
    const prompt = `You are an expert at identifying athletes in photos. I need you to select the BEST image URL that shows "${athleteName}".

ATHLETE INFO:
Name: ${athleteName}
${contextInfo.join('\n')}

CANDIDATE IMAGE URLS:
${urlList}

REQUIREMENTS:
- Must be a clear, professional photo of the athlete
- Should show the person's face clearly
- Avoid team photos or group shots
- Prefer high-quality, official-looking images

Respond in JSON format:
{
  "selectedIndex": <number 1-${imageUrls.length}>,
  "reasoning": "<explanation of why this image is the best match>"
}

If none of the images are suitable, respond with selectedIndex: 0.`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
      temperature: 0.3
    });
    
    const gptResponse = response.choices[0]?.message?.content;
    if (!gptResponse) {
      console.log(`❌ No response from GPT-5 for image selection`);
      return null;
    }
    
    console.log(`🤖 GPT-5 selection response: ${gptResponse}`);
    
    try {
      const selection = JSON.parse(gptResponse);
      
      if (selection.selectedIndex === 0) {
        console.log(`❌ GPT-5 determined no images are suitable: ${selection.reasoning}`);
        return null;
      }
      
      const selectedUrl = imageUrls[selection.selectedIndex - 1];
      console.log(`✅ GPT-5 selected image ${selection.selectedIndex}: ${selectedUrl}`);
      console.log(`📋 Reasoning: ${selection.reasoning}`);
      
      return selectedUrl;
      
    } catch (parseError) {
      console.error(`❌ Error parsing GPT-5 response:`, parseError);
      return null;
    }
    
  } catch (error) {
    console.error(`❌ Error in GPT-5 image selection:`, error);
    return null;
  }
}



// Step 3: Validate image URL accessibility
async function validateImageUrl(url: string): Promise<boolean> {
  try {
    console.log(`🔍 Validating image URL: ${url}`);
    
    const response = await fetch(url, { 
      method: 'HEAD',
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
      }
    });
    
    if (!response.ok) {
      console.log(`❌ Image URL not accessible: ${response.status}`);
      return false;
    }
    
    const contentType = response.headers.get('content-type');
    if (!contentType || !contentType.startsWith('image/')) {
      console.log(`❌ URL is not an image: ${contentType}`);
      return false;
    }
    
    console.log(`✅ Image URL validated successfully`);
    return true;
    
  } catch (error) {
    console.error(`❌ Error validating image URL:`, error);
    return false;
  }
}